# .github/workflows/preview.yml
name: Deploy PR previews

# Add permissions at the top level
permissions:
  contents: write
  pull-requests: write
  deployments: write
  statuses: write

concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Add deployment status
      - name: Start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: pr-preview
          ref: ${{ github.head_ref }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        if: github.event.action != 'closed'
        run: |
          yarn install
          bundle install

      - name: Build CSS
        if: github.event.action != 'closed'
        run: |
          yarn build:css
          mkdir -p ./_site/assets/css/
          cp ./assets/css/main.css ./_site/assets/css/
          cp ./assets/css/tailwind.css ./_site/assets/css/

      - name: Create preview config
        if: github.event.action != 'closed'
        run: |
          echo "baseurl: /pr-preview/pr-${{ github.event.pull_request.number }}" > _config_preview.yml

      - name: Build Jekyll site
        if: github.event.action != 'closed'
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll build --config _config.yml,_config_preview.yml

      - uses: rossjrw/pr-preview-action@v1
        id: preview
        with:
          source-dir: _site
          preview-branch: main
          umbrella-dir: pr-preview
          action: auto
          token: ${{ secrets.GITHUB_TOKEN }}

      # Update deployment status based on the preview deployment
      - name: Update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: pr-preview
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://mada.sfai.org/pr-preview/pr-${{ github.event.pull_request.number }}/

      # Add a comment to the PR with the preview URL
      - uses: marocchino/sticky-pull-request-comment@v2
        if: success() && github.event.action != 'closed'
        with:
          header: preview
          message: |
            🚀 Preview deployment is ready!

            URL: https://mada.sfai.org/pr-preview/pr-${{ github.event.pull_request.number }}/

            Built from commit: ${{ github.sha }}
